### ISSUE TITLE
搬瓦工

### ISSUE THREAD

**Issue by leang521** [esirplayground/VPS_OpenWrt#2]
搬瓦工执行脚本后重启，然后打不开主页，不确定原因

**Comment by esirplayground** [comment]
连接vnc后什么有什么提示？

**Comment by leang521** [comment]
后台显示没有启动起来，不知道卡在那里。点停止和重启都没用，只能强制关闭。后台是KVM

**Comment by esirplayground** [comment]
> 
> 
> 后台显示没有启动起来，不知道卡在那里。点停止和重启都没用，只能强制关闭。后台是KVM

vnc显示内容截屏看一下

**Comment by leang521** [comment]
![1](https://user-images.githubusercontent.com/19215529/126096983-d2657499-e49e-401c-8e43-599abf59628e.jpg)
![2](https://user-images.githubusercontent.com/19215529/126096990-a0000bfb-acf5-4c34-a963-3c8216fa3808.jpg)

**Comment by leang521** [comment]
> > 后台显示没有启动起来，不知道卡在那里。点停止和重启不能用，只能强制关闭。后台是KVM
> 
> vnc显示内容截屏看一下

就是没启动起来

**Comment by esirplayground** [comment]
你用的镜像不是我网盘上提供的server版吧？

**Comment by leang521** [comment]
> 你用的镜像不是我网盘上提供的服务器版吧？

是你网盘上的文件啊，我完全按照你的说明进行的

**Comment by leang521** [comment]
> 你用的镜像不是我网盘上提供的服务器版吧？

能解决吗？等着呢

**Comment by esirplayground** [comment]
> 
> 
> > 你用的镜像不是我网盘上提供的服务器版吧？
> 
> 能解决吗？等着呢

呵
我的固件不会跑码，而且网口部分是设置过的，而你这个跑码，网络接口部分是否配置过也不知道
如果方便就TG联系我，把vps给我测试一下

**Comment by leang521** [comment]
> > > 你用的镜像不是我网盘上提供的服务器版吧？
> > 
> > 
> > 能解决吗？等着呢
> 
> 呵呵
> 我的收费部分不会跑码，网口是设置过的，而你跑这个码，网络接口部分是否配置过也不知道
> 如果方便就TG联系我，把vps给我测试一下

问题有解决吗？
